# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.19.2
loom_version=1.16-SNAPSHOT
# Mod Properties
mod_version=0.3.0-1.21.1
maven_group=net.theblindbandit6
archives_base_name=ToyBricks
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.116.11+1.21.1
